import type { Metadata } from "next";

import "./globals.css";
import { geistMono, geistSans, poppins } from "@/fonts/fonts";
import Navbar from "@/components/navigation/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} text-neutral-800 flex flex-col min-h-screen antialiased bg-gradient-to-r  from-blue-50 to-neutral-50`}
      >
        <header><Navbar /></header>
        <main className=" flex flex-grow">{children}</main>

      </body>
    </html>
  );
}
